package de.randomerror.GUI.view;

import com.intellij.uiDesigner.core.GridLayoutManager;
import de.randomerror.GUI.controller.DeliveryViewController;
import de.randomerror.util.Provided;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Jan on 14.05.2017.
 */
@Provided
public class DeliveryView {
    private DeliveryViewController deliveryController;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
